<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:gra-sirs="http://www.iir.com/SIRS/1.0.0"
                  xmlns:rn="http://www.iir.com/sorna/NIEM/2.1/notification/1.0"
                  xmlns:op="http://www.iir.com/sorna/NIEM/2.1/OP/1.0"
                  xmlns:ope="http://www.iir.com/sorna/NIEM/2.1/OP/extension/1.0"
                  xmlns:rne="http://www.iir.com/sorna/NIEM/2.1/notification/extension/1.0"
                  targetNamespace="http://www.iir.com/SIRS/1.0.0">
   <wsdl:documentation>SIRS provides offender information and notices between stakeholders to track the offender's compliance with SORNA registration requirements</wsdl:documentation>
   <wsp:Policy wsu:Id="wsa_policy">
	     <wsp:ExactlyOne>
		       <wsp:All>
			         <wsaw:UsingAddressing/>	
		       </wsp:All>
	     </wsp:ExactlyOne>
   </wsp:Policy>
   <wsdl:types>
      <xsd:schema>
         <xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/notification/1.0"
                     schemaLocation="../../artifacts/service model/information model/SORNA Relocation IEPD/XMLschemas/exchange/RelNotice.xsd"/>
         <xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/OP/1.0"
                     schemaLocation="../../artifacts/service model/information model/SORNA Relocation IEPD/XMLschemas/exchange/OffPackage.xsd"/>
         <xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/OP/extension/1.0"
                     schemaLocation="../../artifacts/service model/information model/SORNA Relocation IEPD/external/OffPackage-ext.xsd"/>
         <xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/notification/extension/1.0"
                     schemaLocation="../../artifacts/service model/information model/SORNA Relocation IEPD/external/RelNotice-ext.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="SubmitRelocationPackage.RelocationPackage">
      <wsdl:part name="SubmitRelocationPackage.RelocationPackage.RegisteredSexOffenderPackage"
                 element="op:RegisteredSexOffenderPackage">
         <wsdl:documentation>A data type for sex offender relocation package.</wsdl:documentation>
      </wsdl:part>
   </wsdl:message>
   <wsdl:portType name="RelocationPort">
      <wsdl:operation name="SubmitRelocationPackage">
         <wsdl:documentation>The Intermediary Host invokes this action to receive the RelocationPackage message from the Sending Jurisdiction</wsdl:documentation>
         <wsdl:input name="SubmitRelocationPackage.RelocationPackage"
                     message="gra-sirs:SubmitRelocationPackage.RelocationPackage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:portType name="NotificationPort"/>
   <wsdl:binding name="RelocationPortBinding" type="gra-sirs:RelocationPort">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsp:PolicyReference URI="#wsa_policy"/>
      <wsdl:operation name="SubmitRelocationPackage">
         <soap:operation soapAction="SubmitRelocationPackage" style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:binding name="NotificationPortBinding" type="gra-sirs:NotificationPort">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsp:PolicyReference URI="#wsa_policy"/>
   </wsdl:binding>
   <wsdl:service name="ReceivingJurisdictionServiceSIPService">
      <wsdl:port name="RelocationPort" binding="gra-sirs:RelocationPortBinding">
         <soap:address location="http://RelocationPort"/>
      </wsdl:port>
      <wsdl:port name="NotificationPort" binding="gra-sirs:NotificationPortBinding">
         <soap:address location="http://NotificationPort"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
