<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:gra-sirs="http://www.iir.com/SIRS/1.0.0"
                  xmlns:rn="http://www.iir.com/sorna/NIEM/2.1/notification/1.0"
                  xmlns:rne="http://www.iir.com/sorna/NIEM/2.1/notification/extension/1.0"
                  targetNamespace="http://www.iir.com/SIRS/1.0.0">
   <wsdl:documentation>SIRS provides offender information and notices between stakeholders to track the offender's compliance with SORNA registration requirements</wsdl:documentation>
   <wsp:Policy wsu:Id="wsa_policy">
	     <wsp:ExactlyOne>
		       <wsp:All>
			         <wsaw:UsingAddressing/>	
		       </wsp:All>
	     </wsp:ExactlyOne>
   </wsp:Policy>
   <wsdl:types>
      <xsd:schema>
         <xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/notification/1.0"
                     schemaLocation="../../artifacts/service model/information model/SORNA Relocation IEPD/XMLschemas/exchange/RelNotice.xsd"/>
         <xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/notification/extension/1.0"
                     schemaLocation="../../artifacts/service model/information model/SORNA Relocation IEPD/external/RelNotice-ext.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="unNamed.RelocationNotice">
      <wsdl:part name="unNamed.RelocationNotice.SORNARelocationNotice"
                 element="rn:SORNARelocationNotice">
         <wsdl:documentation>A data type for sex offender relocation notice information</wsdl:documentation>
      </wsdl:part>
   </wsdl:message>
   <wsdl:portType name="NotificationPort">
      <wsdl:operation name="unNamed">
         <wsdl:input name="unNamed.RelocationNotice"
                     message="gra-sirs:unNamed.RelocationNotice"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="NotificationPortBinding" type="gra-sirs:NotificationPort">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsp:PolicyReference URI="#wsa_policy"/>
      <wsdl:operation name="unNamed">
         <soap:operation soapAction="RelocationNotification" style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="SendingJuridictionSIPService">
      <wsdl:port name="NotificationPort" binding="gra-sirs:NotificationPortBinding">
         <soap:address location="http://NotificationPort"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
