<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:gra-sirs="http://www.iir.com/SIRS/1.0.0" xmlns:rne="http://www.iir.com/sorna/NIEM/2.1/notification/extension/1.0" targetNamespace="http://www.iir.com/SIRS/1.0.0">
	<wsdl:documentation>SIRS provides offender information and notices between stakeholders to track the offender's compliance with SORNA registration requirements</wsdl:documentation>
	<wsp:Policy wsu:Id="wsa_policy">
	<wsp:ExactlyOne>
		<wsp:All>
			<wsaw:UsingAddressing/>	
		</wsp:All>
	</wsp:ExactlyOne>
</wsp:Policy>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/notification/extension/1.0" schemaLocation="artifacts/service model/information model/SORNA Relocation IEPD/external/RelNotice-ext.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="SORNARelocationNotice">
		<wsdl:part name="SORNARelocationNoticeType" element="rne:SORNARelocationNoticeType">
			<wsdl:documentation>A data type for sex offender relocation notice information</wsdl:documentation>
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="RelocationNoticeInterface">
		<wsdl:operation name="RelocationNotification">
			<wsdl:input name="SORNARelocationNotice" message="gra-sirs:SORNARelocationNotice"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="RelocationNoticeInterfaceBinding" type="gra-sirs:RelocationNoticeInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsp:PolicyReference URI="#wsa_policy"/>
		<wsdl:operation name="RelocationNotification">
			<soap:operation soapAction="RelocationNotice" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="NotificationServiceSIPService ">
		<wsdl:port name="RelocationNoticeInterface" binding="gra-sirs:RelocationNoticeInterfaceBinding">
			<soap:address location="http://RelocationNoticeInterface"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>